### ISSUE TITLE
ProjectTreeTests.ProjectTreeChangesSinceLargeTreeTest sometimes fails

### ISSUE THREAD

**Issue by AArnott** [AArnott/ImmutableObjectGraph#38]
Test runs randomly fail with this error:

    Error Message:
       System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
    Stack Trace:
       at ImmutableObjectGraph.RecursiveTypeExtensions.Find[TRecursiveParent,TRecursiveType](TRecursiveParent parent, UInt32 identity) in f:\vnext1\5a7f96c7\AArnott\ImmutableObjectGraph\src\ImmutableObjectGraph\RecursiveTypeExtensions.cs:line 168
       at ImmutableObjectGraph.Tests.ProjectTree.Find(UInt32 identity) in f:\vnext1\5a7f96c7\AArnott\ImmutableObjectGraph\src\ImmutableObjectGraph.Tests\ProjectTree.generated.cs:line 752
       at ImmutableObjectGraph.Tests.RootedProjectTree.Find(UInt32 identity) in f:\vnext1\5a7f96c7\AArnott\ImmutableObjectGraph\src\ImmutableObjectGraph.Tests\ProjectTree.generated.cs:line 1425
       at ImmutableObjectGraph.Tests.ProjectTreeTests.ProjectTreeChangesSinceLargeTreeTest() in f:\vnext1\5a7f96c7\AArnott\ImmutableObjectGraph\src\ImmutableObjectGraph.Tests\ProjectTreeTests.cs:line 53
    Test Run Failed.

Prior to the error, the test has been observed to produce this output:

    Random seed: 1869664796
    Total tree size: 8280 nodes

**Comment by AArnott** [comment]
This has not repro'd for a long time. It seems from the bug detail that this involved the T4 generator and that's gone now.
