### ISSUE TITLE
Build fails when system culture is set to german

### ISSUE THREAD

**Issue by azeno** [AArnott/ImmutableObjectGraph#43]
I'm getting the following build error (when using the roslyn approach):

    Error The "GenerateCodeFromAttributes" task failed unexpectedly.
    System.NotImplementedException: Die Kultur "Deutsch (Deutschland)" wird nicht unterstützt.Die Pluralisierung wird derzeit nur für die englische Sprache unterstützt.
    at System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(CultureInfo culture)
       at ImmutableObjectGraph.CodeGeneration.CodeGen..ctor(ClassDeclarationSyntax applyTo, Document document, IProgressAndErrors progress, Options options, CancellationToken cancellationToken) in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen.cs:line 75
       at ImmutableObjectGraph.CodeGeneration.CodeGen.<GenerateAsync>d__54.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen.cs:line 88
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at ImmutableObjectGraph.CodeGeneration.DocumentTransform.<TransformAsync>d__2.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration\DocumentTransform.cs:line 55
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.<<Execute>b__28_0>d.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 127
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 98
       at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute()
       at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 55
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() 

The german error message says something like: The culture "German (Germany)" is not supported. Pluralization is only available in the English language.

**Comment by azeno** [comment]
Also note that I get the same error when using T4.

**Comment by AArnott** [comment]
Yes, I figured that would be the case. Not sure how to fix it, other than to just deactivate the feature for cultures that that service doesn't support.

**Comment by azeno** [comment]
How about using an english culture? Source code is written in English anyways. Or did I miss the point of that feature?

**Comment by AArnott** [comment]
Do you mean forcing the code to assume an English culture even though VS is using German? There's an interesting idea. Sure, that should work.

**Comment by azeno** [comment]
Exactly.

**Comment by azeno** [comment]
Any news on this? Should I make a pull request? Would be nice to have nuget package out with this issue fixed.

**Comment by AArnott** [comment]
Yes, please do send a pull request.

**Comment by Sukumi** [comment]
Okay....solved or not? At least with that strange beta package I get from nuget. Besides Versioning is here quite strange. The VS Tools for Lua using your beta and it sucks...also after updating to v1.0.15192-beta7. Nuget gave me 1.0.0 as the latest stable version as a restore option. But the naming is different and besides not compatible with the Lua lang service impl. at all. But they did also not testing that version.
So, what means the the 1.0.0-beta8 milesstone????
And why is the issue it closed. The milestone is not available yet in Git.
Beside the solution given here is really bad. Unbelievable! 
My son is 14 and gets better results with his C++ PS3 coding.
if you dont know how to do it...than dont do it and stop waste the time of many other developer.

I dont know but the general trend to fast-tracking open source activities and throw unfinished, undocumented and untested components to the community is really the perfect way to make nonsense of the open source idea. 
The consumer tests are funny. But for sure not the tests someone would expect here.
Your integration and unit test are not systematic at all and test coverage seems really low. Their effectivity is widely questioned by me anyway.
Okay, who will expect here coverage measurements. I dont see any system and acceptance tests which cover the final verification during a real-life build step. 

Anyway, your tests have been skipped during CI appveyor build with the following result:

Starting test execution, please wait... 
Skipped  PackageLoadTest 
Skipped  CPPWinformsApplication 
Skipped  WinformsApplication 
Skipped  CreateEmptySolution 
Skipped  VBWinformsApplication 
Skipped  CreateInstance 
Skipped  IsIVsPackage
Skipped  SetSite
 
Total tests: 8. Passed: 0. Failed: 0. Skipped: 8. 
Test Run Successful. 
Test execution time: 1.5001 Seconds 

Sorry, bullshit !!!!!!!!!!!!!!!!!!!!!!!!!!!  And nuget is spreading your component with a 1.0.0 stable version label. Get familar with version policy and notation or stop cheating the community.
Your versioning system is not compliant with common standards and not consistent.

Analyzer could not be found and the exception have been swallowed (The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040))
Search for different job or dont start a job which you can run nor finish.

Looked up older builds...similar. 

That Nuget spread every piece of shit to the community is really bad. No quality standards nor quality control.

**Comment by AArnott** [comment]
@Sukumi I don't know what you're talking about. Did you file this issue against the wrong project? What does C++ PS3, or the tests you mentioned, or analyzer bugs have to do with this project? It looks quite irrelevant.
That, and your very offensive, vulgar choice of words leads me to remove/trim your comment for the benefit of the broader community.
If you'd like to try again with a more constructive and relevant dialog for this project, I'd welcome your feedback.
