### ISSUE TITLE
Design-time builds fail during code generation on VS2015 Update 1 RC

### ISSUE THREAD

**Issue by jviau** [AArnott/ImmutableObjectGraph#56]
The following warning shows up after project reload after generating immutable objects. Intellisense across the entire project is broken as a result.

**Repro steps**

1. Create a C# console application project (I targeted .NET 4.6)
1. `Install-Package ImmutableObjectGraph.Generation -Pre -Version 1.0.15192-beta7`
1. Follow the steps in the readme.txt that appears to define your first immutable object.
1. Reload the solution.
1. Build the project. The build should succeed.

**Expected (observed on VS2015 RTM)**
Intellisense works and Error List is free of errors

**Actual (observed on VS2015 Update 1 RC - vsuvscore 24623.00)**
All open documents from the project are associated with the "Miscellaneous Files" project in the context dropdown.

You *may* also see this in the error list appear as a warning: (This is with a build of Roslyn from Oct 14th and VS 2015.)

```
The "GenerateCodeFromAttributes" task failed unexpectedly.
System.IO.FileLoadException: 
Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)File name: 'Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'   
at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.<Execute>b__28_0()   
at System.Threading.Tasks.Task`1.InnerInvoke()   
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 98   
at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute() 
at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 55   
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by AArnott** [comment]
Fixed by ac0c22ca
