### ISSUE TITLE
The "GenerateCodeFromAttributes" task failed unexpectedly when DefineRootedStruct = True on nested immutable

### ISSUE THREAD

**Issue by jviau** [AArnott/ImmutableObjectGraph#57]
The objects are as follows:

```C#
    [GenerateImmutable(GenerateBuilder = true, DefineRootedStruct = true)]
    public partial class Node
    {
        readonly string name;
        readonly ImmutableHashSet<string> tags;
    }

    [GenerateImmutable(GenerateBuilder = true)]
    public partial class Tree
    {
        readonly ImmutableSortedSet<Tree> children;
        readonly Node node;
    }
```

This results in the following build error:

```
The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Undefined type.
Parameter name: metaType
   at ImmutableObjectGraph.CodeGeneration.CodeGen.RootedStructGen.GetRootedTypeSyntax(MetaType metaType) in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen+RootedStructGen.cs:line 70
   at ImmutableObjectGraph.CodeGeneration.CodeGen.RootedStructGen.CreateRootProperty() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen+RootedStructGen.cs:line 429
   at ImmutableObjectGraph.CodeGeneration.CodeGen.RootedStructGen.CreateRootedStruct() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen+RootedStructGen.cs:line 176
   at ImmutableObjectGraph.CodeGeneration.CodeGen.RootedStructGen.GenerateCore() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen+RootedStructGen.cs:line 107
   at ImmutableObjectGraph.CodeGeneration.CodeGen.<GenerateAsync>d__56.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ImmutableObjectGraph.CodeGeneration.CodeGen.<GenerateAsync>d__54.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Roslyn\CodeGen.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ImmutableObjectGraph.CodeGeneration.DocumentTransform.<TransformAsync>d__2.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration\DocumentTransform.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.<<Execute>b__28_0>d.MoveNext() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 98
   at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Helper.Execute()
   at ImmutableObjectGraph.CodeGeneration.Tasks.GenerateCodeFromAttributes.Execute() in C:\Users\andarno\git\ImmutableObjectGraph\src\ImmutableObjectGraph.CodeGeneration.Tasks\GenerateCodeFromAttributes.cs:line 55
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ImmutableGraph
```

**Comment by jviau** [comment]
I assume this fails due to Node not being a graph structure. The reason I put "DefineRootedStructer = true" on it was because the readme says to keep properties consistent and it was failing without it on there as well. However, I found that DefineRootedStructer = true will succeed on only the Tree if the Tree also has DefineWithMethodsPerProperty = true. This should be documented somewhere.

**Comment by AArnott** [comment]
Possibly related to #44

**Comment by AArnott** [comment]
Looking into this one now.

**Comment by AArnott** [comment]
It looks like your `Node` class should not set `DefineRootedStruct = true` since it's not a direct part of a recursive object tree (only an appendage to it).
The fix I'm working toward is to emit a warning in this case but otherwise proceed to generate valid code.

**Comment by AArnott** [comment]
After fixing this, I found that the code generator succeeds, but generates code that doesn't compile.
I've modified your repro slightly to isolate the particular error you were reporting. I'll file another issue to track the remaining compilation errors.
