### ISSUE TITLE
Didn't work right out the gate

### ISSUE THREAD

**Issue by DamianReeves** [AArnott/ImmutableObjectGraph#73]
Create a new class library targeting .NET 4.5.2 with the latest version **1.1.68-beta** from nuget and it fails to build with the following error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateCodeFromAttributes" task failed unexpectedly.
System.InvalidOperationException: Unable to find code generator: ImmutableObjectGraph.Generation.CodeGenerator, ImmutableObjectGraph.Generation, Version=1.1.0.0, Culture=neutral, PublicKeyToken=bfd91f1bd601e0d7
   at Validation.Verify.Operation(Boolean condition, String unformattedMessage, Object arg1)
   at CodeGeneration.Roslyn.DocumentTransform.<FindCodeGenerators>d__3.MoveNext()
   at CodeGeneration.Roslyn.DocumentTransform.<TransformAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.<<Execute>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.Execute()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.Execute()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ImmutableStuff			

```

**Comment by AArnott** [comment]
Wow. I see what you mean. I also note that far too many nuget dependencies are brought in by the library. I'll get this fixed asap.

**Comment by AArnott** [comment]
For now, I've unlisted all versions after 1.1.7-beta from nuget.org since they appear to be broken. You can pick up 1.1.7-beta to get unblocked for now. I'll still get to this as soon as I can.

**Comment by azeno** [comment]
Any updates on this?

**Comment by AArnott** [comment]
Whoops. Thanks for checking. I've been swamped. But I do want to get to this. I guess I can't promise exactly when.

**Comment by AArnott** [comment]
The public v1.1.77-beta release should work "right out the gate". :)

**Comment by azeno** [comment]
It does indeed. Thanks!

**Comment by AArnott** [comment]
Yay! Thanks for the confirmation.
