### ISSUE TITLE
Fails on byte array field

### ISSUE THREAD

**Issue by DamianReeves** [AArnott/ImmutableObjectGraph#75]
The code fails to work with a byte array field:

```C#
    [GenerateImmutable]
    public partial class AccessToken
    {
        readonly string accessKey;
        readonly byte[] secret;
    }
```

**Comment by AArnott** [comment]
How does it fail? `byte[]` isn't immutable, so given immutability is the presumed goal, have you tried `ImmutableArray<byte>`?

**Comment by IanYates** [comment]
I had the same problem and then the same forehead slapping realisation that ImmutableList<byte> was the answer, although one time I was happy enough with a base64 string since I was using my immutable object as a DTO via JSON.NET and SignalR anyway.
I guess some automatic conversion of common array or collection types to ImmutableList would be handy for newcomers.

**Comment by AArnott** [comment]
Thanks, @IanYates. Although I'll offer that `ImmutableList<T>` is a really bad substitute for a `byte[]` because of `ImmutableList<T>`'s internal data structure being *much* more expensive than an array. That's why `ImmutableArray<T>` is preferable when you don't need fast incremental mutation-by-copy, which is where `ImmutableList<T>` shines.

We can't automatically convert a `byte[]` in the source to one of these, because the field you supply ends up in the final code. While we can add a property getter and setter that exposed the field as this other collection type, it would require copying the data on every get and set call, which would be super inefficient.

I suspect the "fix" here is for the IOG generator to flag use of `byte[]` (or any array type) as an error and suggest use of `ImmutableArray<T>` instead.

**Comment by IanYates** [comment]
Good point
```
We can't automatically convert a byte[] in the source to one of these, because the field you supply ends up in the final code. While we can add a property getter and setter that exposed the field as this other collection type, it would require copying the data on every get and set call, which would be super inefficient.
```
Although I'm still on the T4 templates where such anarchy can occur :)

Agreed about ImmutableArray making more sense for this purpose.

**Comment by AArnott** [comment]
> Although I'm still on the T4 templates where such anarchy can occur :)

True. :) The T4 approach did let the generator rewrite the fields. That was nice because it could add attributes to the fields (like hiding them from the debugger display by default).

**Comment by AArnott** [comment]
Given the original repro, the code generation task fails with this error:

```
The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.VariableDeclaration(TypeSyntax type, SeparatedSyntaxList`1 variables)
   at ImmutableObjectGraph.Generation.CodeGen.<>c.<CreateTemplateStruct>b__69_0(MetaField f) in C:\Users\andre\git\ImmutableObjectGraph\src\ImmutableObjectGraph.Generation\CodeGen.cs:line 364
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at ImmutableObjectGraph.Generation.CodeGen.CreateTemplateStruct() in C:\Users\andre\git\ImmutableObjectGraph\src\ImmutableObjectGraph.Generation\CodeGen.cs:line 361
   at ImmutableObjectGraph.Generation.CodeGen.<GenerateAsync>d__58.MoveNext() in C:\Users\andre\git\ImmutableObjectGraph\src\ImmutableObjectGraph.Generation\CodeGen.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ImmutableObjectGraph.Generation.CodeGen.<GenerateAsync>d__56.MoveNext() in C:\Users\andre\git\ImmutableObjectGraph\src\ImmutableObjectGraph.Generation\CodeGen.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CodeGeneration.Roslyn.DocumentTransform.<TransformAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.<<Execute>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.Execute()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.Execute()
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
